<a href="https://colab.research.google.com/github/NaraGuimma/Imersao_Python_2021/blob/main/Projeto1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

Passo 1 - Importar base de dados

In [2]:
tabela_vendas = pd.read_excel("/content/drive/MyDrive/Imersão Python 2021/Aula 1/Vendas.xlsx")
display(tabela_vendas)

        Código Venda       Data  ... Valor Unitário Valor Final
0                  1 2019-01-01  ...            358         358
1                  1 2019-01-01  ...            180         360
2                  1 2019-01-01  ...            368         368
3                  2 2019-01-02  ...            200         600
4                  2 2019-01-02  ...             71          71
...              ...        ...  ...            ...         ...
100994         69996 2019-12-26  ...            102         204
100995         69996 2019-12-26  ...            270        1080
100996         69996 2019-12-26  ...             87          87
100997         69997 2019-12-26  ...            108         108
100998         69997 2019-12-26  ...            133         266

[100999 rows x 7 columns]

In [3]:
tabela_vendas.head(5)

   Código Venda       Data  ... Valor Unitário Valor Final
0             1 2019-01-01  ...            358         358
1             1 2019-01-01  ...            180         360
2             1 2019-01-01  ...            368         368
3             2 2019-01-02  ...            200         600
4             2 2019-01-02  ...             71          71

[5 rows x 7 columns]

In [4]:
tabela_vendas.tail(5)

        Código Venda       Data  ... Valor Unitário Valor Final
100994         69996 2019-12-26  ...            102         204
100995         69996 2019-12-26  ...            270        1080
100996         69996 2019-12-26  ...             87          87
100997         69997 2019-12-26  ...            108         108
100998         69997 2019-12-26  ...            133         266

[5 rows x 7 columns]

In [5]:
tabela_vendas.describe()

        Código Venda     Quantidade  Valor Unitário    Valor Final
count  100999.000000  100999.000000   100999.000000  100999.000000
mean    34923.310429       2.165249      191.861018     414.628491
std     20227.910360       1.257710      145.414462     434.093054
min         1.000000       1.000000       30.000000      30.000000
25%     17461.000000       1.000000      100.000000     156.000000
50%     34842.000000       2.000000      155.000000     274.000000
75%     52502.000000       3.000000      248.000000     524.000000
max     69997.000000       5.000000      750.000000    3750.000000

**Passo 2 - Calcular o faturamento da loja**

In [8]:
tabela_faturada = tabela_vendas[['ID Loja', 'Valor Final']]

In [9]:
tabela_faturada.head(5)

              ID Loja  Valor Final
0  Iguatemi Esplanada          358
1  Iguatemi Esplanada          360
2  Iguatemi Esplanada          368
3      Norte Shopping          600
4      Norte Shopping           71

In [11]:
tabela_faturada.groupby(['ID Loja']).sum()

                                  Valor Final
ID Loja
Bourbon Shopping SP                   1726110
Center Shopping Uberlândia            1668921
Iguatemi Campinas                     1762419
Iguatemi Esplanada                    1699681
Norte Shopping                        1711968
Novo Shopping Ribeirão Preto          1678225
Palladium Shopping Curitiba           1721120
Parque Dom Pedro Shopping             1631630
Passei das Águas Shopping             1649014
Ribeirão Shopping                     1707122
Rio Mar Recife                        1722766
Rio Mar Shopping Fortaleza            1698430
Salvador Shopping                     1646739
Shopping Barra                        1653103
Shopping Center Interlagos            1640486
Shopping Center Leste Aricanduva      1682870
Shopping Eldorado                     1648111
Shopping Ibirapuera                   1635060
Shopping Iguatemi Fortaleza           1674824
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444
Shopping Recife                       1624879
Shopping SP Market                    1721763
Shopping União de Osasco              1663770
Shopping Vila Velha                   1731167

groupby - agrupar os dados em uma coluna


sum - somar os valores de outra coluna que contenha núúmeros

In [13]:
faturamento = tabela_vendas[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()
faturamento = faturamento.sort_values(by='Valor Final', ascending=False)
display(faturamento)

                                  Valor Final
ID Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

**Passo 3 - Quantidade vendida por loja**

In [14]:
quantidade = tabela_vendas[['ID Loja', 'Quantidade']].groupby('ID Loja').sum()
quantidade = quantidade.sort_values(by='ID Loja', ascending=False)
display(quantidade)

                                  Quantidade
ID Loja
Shopping Vila Velha                     9224
Shopping União de Osasco                8730
Shopping SP Market                      8927
Shopping Recife                         8581
Shopping Morumbi                        8508
Shopping Midway Mall                    8206
Shopping Iguatemi Fortaleza             8629
Shopping Ibirapuera                     8723
Shopping Eldorado                       8719
Shopping Center Leste Aricanduva        8938
Shopping Center Interlagos              8675
Shopping Barra                          8638
Salvador Shopping                       8698
Rio Mar Shopping Fortaleza              8937
Rio Mar Recife                          8863
Ribeirão Shopping                       8825
Passei das Águas Shopping               8618
Parque Dom Pedro Shopping               8388
Palladium Shopping Curitiba             9091
Novo Shopping Ribeirão Preto            8751
Norte Shopping                          9014
Iguatemi Esplanada                      8580
Iguatemi Campinas                       8935
Center Shopping Uberlândia              8627
Bourbon Shopping SP                     8863

**Passo 4 - Calculando o Ticket Médio dos Produtos por Loja**

In [15]:
ticket_medio = (faturamento['Valor Final'] / quantidade['Quantidade']).to_frame()
ticket_medio = ticket_medio.rename(columns={0: 'Ticket Medio'})
ticket_medio = ticket_medio.sort_values(by='Ticket Medio', ascending=False)
display(ticket_medio)

                                  Ticket Medio
ID Loja
Iguatemi Esplanada                  198.098019
Iguatemi Campinas                   197.248909
Bourbon Shopping SP                 194.754598
Parque Dom Pedro Shopping           194.519552
Rio Mar Recife                      194.377299
Shopping Iguatemi Fortaleza         194.092479
Shopping Midway Mall                193.814404
Center Shopping Uberlândia          193.453228
Ribeirão Shopping                   193.441586
Shopping SP Market                  192.871401
Novo Shopping Ribeirão Preto        191.775226
Shopping Barra                      191.375666
Passei das Águas Shopping           191.345324
Shopping União de Osasco            190.580756
Rio Mar Shopping Fortaleza          190.044758
Norte Shopping                      189.923231
Shopping Recife                     189.357767
Salvador Shopping                   189.323868
Palladium Shopping Curitiba         189.321307
Shopping Center Interlagos          189.105014
Shopping Eldorado                   189.025232
Shopping Center Leste Aricanduva    188.282614
Shopping Vila Velha                 187.680724
Shopping Ibirapuera                 187.442394
Shopping Morumbi                    186.464974

**Passo 5 - Enviar os e-mails**

In [ ]:
import smtplib
import email.message

server = smtplib.SMTP('smtp.gmail.com:587')  
corpo_email = "Corpo do E-mail"
  
msg = email.message.Message()
msg['Subject'] = "Assunto do E-mail"
  
# Fazer antes (apenas na 1ª vez): Ativar Aplicativos não Seguros.
  # Gerenciar Conta Google -> Segurança -> Aplicativos não Seguros -> Habilitar
# Caso mesmo assim dê o erro: smtplib.SMTPAuthenticationError: (534,
# Você faz o login no seu e-mail e depois entra em: https://accounts.google.com/DisplayUnlockCaptcha
msg['From'] = 'remetente@gmail.com'
msg['To'] = 'destinatario@gmail.com'
password = "senha"
msg.add_header('Content-Type', 'text/html')
msg.set_payload(corpo_email )
  
s = smtplib.SMTP('smtp.gmail.com: 587')
s.starttls()
# Login Credentials for sending the mail
s.login(msg['From'], password)
s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
print('Email enviado')

**Passo 5 - Enviar os e-mails - Parte 2**

In [ ]:
import smtplib
import email.message

def enviar_email(resumo_loja, loja):

  server = smtplib.SMTP('smtp.gmail.com:587')  
  email_content = f'''
  <p>Coe Lira,</p>
  {resumo_loja.to_html()}
  <p>Tmj</p>'''
  
  msg = email.message.Message()
  msg['Subject'] = f'Lira Rules - Loja: {loja}'
  
  
  msg['From'] = 'remetente@gmail.com'
  msg['To'] = 'destinatario@gmail.com'
  password = senha
  msg.add_header('Content-Type', 'text/html')
  msg.set_payload(email_content)
  
  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
  # Login Credentials for sending the mail
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))

Passo 6 - Calculando Indicadores por Loja + Enviar E-mail para todas as lojas

In [ ]:
# email para diretoria

tabela_diretoria = faturamento.join(quantidade).join(ticket_medio)
enviar_email(tabela_diretoria, 'Todas as Lojas')

In [ ]:
lojas = df['ID Loja'].unique()

for loja in lojas:
  tabela_loja = df.loc[df['ID Loja'] == loja, ['ID Loja', 'Quantidade', 'Valor Final']]
  resumo_loja = tabela_loja.groupby('ID Loja').sum()
  resumo_loja['Ticket Médio'] = resumo_loja['Valor Final'] / resumo_loja['Quantidade']
  enviar_email(resumo_loja, loja)